services:
  sqlpreviewservice:
    container_name: sqlpreviewcont
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: mssql
    ports: 
      - "1433:1433"
    environment:
      - SA_PASSWORD=Strong2@PWD12
      - ACCEPT_EULA=Y    
    volumes:
      - /home/melanie/Documents:/mnt/Documents
    privileged: true